#!/usr/bin/env bash

while [[ ! -f yamot_server_settings.json ]]; do
    python3 yamot_server_setup.py
done

python3 yamot_server.py &
pid=$!

./yamot-desktop

kill $pid 2> /dev/null
echo Stopped server
